### ISSUE TITLE
Fix long description associated pypi package

### ISSUE THREAD

**Issue by jcfr** [InsightSoftwareConsortium/ITKColorNormalization#15]
Instead of:

https://github.com/InsightSoftwareConsortium/ITKColorNormalization/blob/b65eb0f8f16ee77dfb2c5b8720acf85a6d6a5b96/setup.py#L23

Consider doing something like this:

```
with open('README.md', 'r') as fp:
    readme = fp.read()
```

and add the following arguments to the setup function:

```
    long_description=readme,
    long_description_content_type='text/markdown',
```

For example, see https://github.com/CastXML/CastXML-python-distributions/blob/master/setup.py

**Comment by thewtex** [comment]
:+1: good idea @jcfr .

After implemented here, this should be added to [ITKModuleTemplate](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate).
