### ISSUE TITLE
not working for some H&E images

### ISSUE THREAD

**Issue by Mr-TalhaIlyas** [InsightSoftwareConsortium/ITKColorNormalization#23]
I attached a sample image on which it is not working and through following error.
RuntimeError: D:\a\im\include\itkStructurePreservingColorNormalizationFilter.hxx:156:
itk::ERROR: The image to be normalized could not be processed; does it have white, blue, and pink pixels?
![img_Adrenal_gland_3_01134](https://user-images.githubusercontent.com/73260385/112558108-55342100-8e11-11eb-948f-e3793c4d071a.png)

**Comment by SahPet** [comment]
Same problem here:
`RuntimeError: D:\a\im\include\itkStructurePreservingColorNormalizationFilter.hxx:181:
ITK ERROR: The reference image could not be processed; does it have white, blue, and pink pixels?`

**Comment by dzenanz** [comment]
Well, this image doesn't have any blue pixels. Is it supposed to work @Leengit?

**Comment by Leengit** [comment]
The algorithm should work if there are pixels with only a little blue, but not if the pixels are all different shades of pink / red.  I cannot see whether the darker pixels in this image are dark red or have a little blue too.  Was this image stained with hematoxylin too?

**Comment by Leengit** [comment]
A bug that is directly related to this issue was identified and fixed with Pull Request #30.  If this has not fixed the present problem, please reopen this issue or open a new one.
